//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public Doctor()
        {
            this.Doctor_Rating = new HashSet<Doctor_Rating>();
            this.Templates = new HashSet<Template>();
            this.Visitations = new HashSet<Visitation>();
        }
    
        public long doctor_Id { get; set; }
        public long hospital_Id { get; set; }
        public string first_name { get; set; }
        public string second_name { get; set; }
        public string last_name { get; set; }
        public string specialization { get; set; }
        public long rating { get; set; }
    
        public virtual Hospital Hospital { get; set; }
        public virtual ICollection<Doctor_Rating> Doctor_Rating { get; set; }
        public virtual ICollection<Template> Templates { get; set; }
        public virtual ICollection<Visitation> Visitations { get; set; }
    }
}
