//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital_Rating
    {
        public long patient_Id { get; set; }
        public long hospital_Id { get; set; }
        public int rating { get; set; }
    
        public virtual Hospital Hospital { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
