//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital
    {
        public Hospital()
        {
            this.Doctors = new HashSet<Doctor>();
            this.Hospital_Rating = new HashSet<Hospital_Rating>();
            this.Templates = new HashSet<Template>();
            this.Visitations = new HashSet<Visitation>();
        }
    
        public long hospital_id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public long rating { get; set; }
    
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual ICollection<Hospital_Rating> Hospital_Rating { get; set; }
        public virtual ICollection<Template> Templates { get; set; }
        public virtual ICollection<Visitation> Visitations { get; set; }
    }
}
