//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalDatabaseEntities : DbContext
    {
        public HospitalDatabaseEntities()
            : base("name=HospitalDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Hospital> Hospitals { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Recommended_Health_Hobbies> Recommended_Health_Hobbies { get; set; }
        public virtual DbSet<Recommended_Visitations> Recommended_Visitations { get; set; }
        public virtual DbSet<Doctor_Rating> Doctor_Rating { get; set; }
        public virtual DbSet<Hospital_Rating> Hospital_Rating { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
        public virtual DbSet<Visitation> Visitations { get; set; }
    }
}
