//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.Doctor_Rating = new HashSet<Doctor_Rating>();
            this.Hospital_Rating = new HashSet<Hospital_Rating>();
            this.Templates = new HashSet<Template>();
            this.Visitations = new HashSet<Visitation>();
        }
    
        public long patient_Id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string first_name { get; set; }
        public string second_name { get; set; }
        public string last_name { get; set; }
        public string egn { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public int gender_id { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual ICollection<Doctor_Rating> Doctor_Rating { get; set; }
        public virtual ICollection<Hospital_Rating> Hospital_Rating { get; set; }
        public virtual ICollection<Template> Templates { get; set; }
        public virtual ICollection<Visitation> Visitations { get; set; }
    }
}
