//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recommended_Health_Hobbies
    {
        public long hobby_Id { get; set; }
        public string name { get; set; }
        public string recurrency { get; set; }
        public string description { get; set; }
        public Nullable<int> min_recommended_age { get; set; }
        public Nullable<int> max_recommended_age { get; set; }
    }
}
